/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Atxy2k.CustomTextField.RestrictedTextField;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author mayka
 */
public class Principal extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;

    Thread h1 = new hilo1();
    Thread h2 = new hilo2();
    Thread h3 = new hilo3();
    Thread h4 = new hilo4();

    int n1 = 0, n2 = 0, n3 = 0, n4 = 0, c = 0, s = 0;

    boolean bandera = true;

    class hilo1 extends Thread {

        @Override
        public void run() {
            do {
                try {
                    n1 = Codigo.Numeros();
                    t1.setText(String.valueOf(n1));
                    Thread.sleep(800);
                } catch (Exception ex) {

                }
            } while (true);
        }
    }

    class hilo2 extends Thread {

        @Override
        public void run() {
            do {
                try {
                    n2 = Codigo.Numeros();
                    t2.setText(String.valueOf(n2));
                    Thread.sleep(800);
                } catch (Exception ex) {

                }
            } while (true);
        }
    }

    class hilo3 extends Thread {

        @Override
        public void run() {
            do {
                try {
                    n3 = Codigo.Numeros();
                    t3.setText(String.valueOf(n3));
                    Thread.sleep(800);
                } catch (Exception ex) {

                }
            } while (true);
        }
    }

    class hilo4 extends Thread {

        @Override
        public void run() {
            do {
                try {
                    n4 = Codigo.Numeros();
                    t4.setText(String.valueOf(n4));
                    Thread.sleep(800);
                } catch (Exception ex) {

                }
            } while (true);
        }
    }

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        pintarImagen(this.jLabel1, "src/Imagenes/fondo3.jpg");
        bloqueo();
        modTextField();
        btnDetener.setVisible(false);
        bloqRuleta();
    }

    public void bloqRuleta() {
        t1.setEditable(false);
        t2.setEditable(false);
        t3.setEditable(false);
        t4.setEditable(false);
        t1.setEnabled(false);
        t2.setEnabled(false);
        t3.setEnabled(false);
        t4.setEnabled(false);
    }

    private void pintarImagen(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
    }

    private void modTextField() {
        textbonito("Ganador", txtGanador);
    }

    private void bloqueo() {
        restricted(4, txtGanador, true);
    }

    private void restricted(int num, JTextField g, boolean soloNum) {
        RestrictedTextField bloqueo = new RestrictedTextField(g);
        bloqueo.setLimit(num);
        bloqueo.setOnlyNums(soloNum);
    }

    private void textbonito(String texto, JTextField g) {
        ModiText mod = new ModiText(texto, g);
    }

    private boolean solo4() {
        String temporal = txtGanador.getText();
        if (temporal.length() == 4) {
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtGanador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Bempezar = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        btnDetener = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego del Casino");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Super Dream", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Generador de Números Pseudoaleatorios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 580, 60));

        txtGanador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtGanador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGanadorActionPerformed(evt);
            }
        });
        txtGanador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGanadorKeyTyped(evt);
            }
        });
        getContentPane().add(txtGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 190, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, -1));

        Bempezar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Bempezar.setText("Empezar");
        Bempezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BempezarMouseClicked(evt);
            }
        });
        Bempezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BempezarActionPerformed(evt);
            }
        });
        getContentPane().add(Bempezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        t1.setFont(new java.awt.Font("Tahoma", 1, 150)); // NOI18N
        t1.setText("9");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, 150));

        t2.setFont(new java.awt.Font("Tahoma", 1, 150)); // NOI18N
        t2.setText("9");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, 150));

        t3.setFont(new java.awt.Font("Tahoma", 1, 150)); // NOI18N
        t3.setText("9");
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 110, 150));

        t4.setFont(new java.awt.Font("Tahoma", 1, 150)); // NOI18N
        t4.setText("9");
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 110, 150));

        btnDetener.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnDetener.setText("Detener");
        btnDetener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetenerMouseClicked(evt);
            }
        });
        btnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BempezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BempezarActionPerformed

    }//GEN-LAST:event_BempezarActionPerformed

    private void txtGanadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGanadorKeyTyped

    }//GEN-LAST:event_txtGanadorKeyTyped

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetenerActionPerformed

    private void txtGanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGanadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGanadorActionPerformed

    private void BempezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BempezarMouseClicked
        //if()
        if (solo4() == true) {
            Bempezar.setVisible(false);
            txtGanador.setEditable(false);
            txtGanador.setEnabled(false);
            btnDetener.setVisible(true);
            System.out.println("hola hola");

            if (bandera == false) {

                System.out.println("false");
                h1.resume();
                h2.resume();
                h3.resume();
                h4.resume();

            } else {
                System.out.println("true");
                h1.start();
                h2.start();
                h3.start();
                h4.start();
                bandera = false;
            }
        } else
            JOptionPane.showMessageDialog(this, "Ingresa un número de 4 dijitos", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_BempezarMouseClicked
    private boolean acierto(int pos, char obtenido) {
        return txtGanador.getText().charAt(pos) == obtenido;
    }

    private void btnDetenerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetenerMouseClicked
        c++;
        switch (c) {
            case 1:
                    h1.suspend();
                 if(!acierto(c - 1, t1.getText().charAt(0))) {
                    h2.suspend();
                    h3.suspend();
                    h4.suspend();
                    accion("Suerte para la próxima");
                }
                break;
            case 2:
                    h2.suspend();
                if(!acierto(c - 1, t2.getText().charAt(0))) {
                    h3.suspend();
                    h4.suspend();
                    accion("Suerte para la próxima");
                }
                break;
            case 3:
                    h3.suspend();
                if(!acierto(c - 1, t3.getText().charAt(0))) {
                    h4.suspend();
                    accion("Suerte para la próxima");
                }
                break;
            case 4:
                     h4.suspend();
                if (acierto(c - 1, t4.getText().charAt(0))) 
                    accion("Has Ganado");
                 else
                    accion("Suerte para la próxima");
                break;
        }
    }//GEN-LAST:event_btnDetenerMouseClicked
    public void accion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        Bempezar.setVisible(true);
        txtGanador.setEditable(true);
        txtGanador.setEnabled(true);
        btnDetener.setVisible(false);
        c=0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bempezar;
    private javax.swing.JButton btnDetener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField txtGanador;
    // End of variables declaration//GEN-END:variables
}
